### ISSUE TITLE
Undertermined values being added when run the script

### ISSUE THREAD

**Issue by rominiti** [vhsantos/centreon_report_to_pdf#12]
From the centreon UI we can see that undetermined is 0%
![centreon](https://user-images.githubusercontent.com/16564391/236243636-39408299-02ca-4576-a6fb-7648c88a8ca4.png)

But checking the csv created by the script it's changing these values to 3.33% for monthly and 25.02% to weekly but I was not able to figure out where it is getting this value.

![centreon2](https://user-images.githubusercontent.com/16564391/236244287-62db1d94-e4d0-413b-912b-ca521cac15ba.png)

centreon version 22.04.2

**Comment by vhsantos** [comment]
Hello @rominiti ,

Usually that happen when the timezone on the configuration of the centreon_report_to_pdf is not set (utc by default) or incorrect. Check your configuration, [here](https://github.com/vhsantos/centreon_report_to_pdf/blob/1e5d7074e2a440317d40fd49cdebe7e64901edc0/centreon_report_to_pdf/config_example.ini#L16) an example.

**Comment by rominiti** [comment]
it works like a charm(muito obrigado)
