### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by p1mpst4r** [vhsantos/centreon_report_to_pdf#7]
Hello, 
i've just installed you module and, on the test i received this error: 

# python centreon_report_to_pdf.py -c config2.ini
Traceback (most recent call last):
  File "centreon_report_to_pdf.py", line 13, in <module>
    build_report()
  File "/root/centreon_report_to_pdf/BuildPDF.py", line 668, in build_report
    csv_url = prepare_csv_url()
  File "/root/centreon_report_to_pdf/Settings.py", line 401, in prepare_csv_url
    (Period_Start,  Periodo_End) = convert_periodo_to_timestamp()
  File "/root/centreon_report_to_pdf/Settings.py", line 377, in convert_periodo_to_timestamp
    start_date = start_date.astimezone(server_timezone)
UnboundLocalError: local variable 'start_date' referenced before assignment

any help will be appreciated.

thanks in advance

Lorenzo

**Comment by vhsantos** [comment]
HI,

did you setup the "[period](https://github.com/vhsantos/centreon_report_to_pdf/blob/909e6e3416363753a7e1d560f2e002b90b5d65ae/centreon_report_to_pdf/config_example.ini#L22)" parameter ??

If you still have problems, share your configuration file (taking off the sensitive data).

Attentive

**Comment by p1mpst4r** [comment]
Hello Victor... i managed to solve all the problems that (not surpised,) where all caused by my mistakes or misinterpretations of your wanderful code.

Thank you very much for your care of my problem.

Regards.

Lorenzo

**Comment by vhsantos** [comment]
Nice to know.
